remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Tài liệu sử dụng Base Checkin-in Client
description: Hướng dẫn sử dụng, các thông tin cần biết khi sử dụng Base Checkin-in Client