baseurl: "/base-checkin-client-documentation"

title: Tài liệu sử dụng Base Checkin-in Client
description: Hướng dẫn sử dụng, các thông tin cần biết khi sử dụng Base Checkin-in Client

remote_theme: just-the-docs/just-the-docs

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.ico"

search_enabled: true
search:
  rel_url: true
  button: true

aux_links:
  "Base.vn":
    - "https://base.vn/"
  "Documentation on GitHub":
    - "https://github.com/hieutbui/base-checkin-client-documentation"
aux_links_new_tab: true

nav_enabled: true

header_anchors: true

footer_content: 'Copyright &copy; 2025 <a href="https://github.com/hieutbui" target="_blank" >Bùi Trung Hiếu</a>. Distributed by an <a href="https://github.com/hieutbui/base-checkin-client-documentation/tree/main/LICENSE" target="_blank">MIT license.</a>'

back_to_top: true
back_to_top_text: "Lên đầu trang"

exclude:
  [
    "README.md",
    "LICENSE",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "CHANGELOG.md",
    "README",
    "SECURITY.md"
  ]
