name: Build Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "docs"
  cancel-in-progress: true
jobs:
  docs:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Jekyll
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          bundle install
          bundle exec jekyll build